#!/usr/bin/env python3

import helpers
import sys

# My code

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets userName")
    
    # instantiate analyzer
    analyzer = Analyzer()
    
    # analyzing tweets and show result 
    userName = sys.argv[1]
    tweetsList = helpers.get_user_timeline(userName, 50)
    for tweet in tweetsList:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(score, "green"), " ", colored(tweet, "green"))
        elif score < 0.0:
            print(colored(score, "red"), " ", colored(tweet, "red"))
        else:
            print(colored(score, "yellow"), " ", colored(tweet, "yellow"))
            
if __name__ == "__main__":
    main()
